name: Check

on:
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Run check project
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Install and cache nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Install packages
        run: pnpm i --ignore-scripts
      - name: Check project
        run: |
          pnpm run ci-check
