name: Check

on:
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Run check project
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Launch Turbo Remote Cache Server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1.3.0
      - name: Install and cache nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install packages
        run: pnpm i --ignore-scripts
      - name: Check project
        run: |
          pnpm run ci-check
