name: Playwright Tests

on:
  pull_request:
    branches: [main]

jobs:
  Playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Run playwright tests
    steps:
      - uses: actions/checkout@v4
      - name: Launch Turbo Remote Cache Server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1.3.0
      - name: Install and cache nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9.2.0
          run_install: false
      - name: Install packages
        run: pnpm i --ignore-scripts
      - name: Install playwright browsers
        run: | 
          pnpm exec playwright install --with-deps chromium
          pnpm exec playwright install --with-deps webkit
      - name: Build packages
        run: pnpm build:packages
      - name: Run integration-test
        run: pnpm integration-test
