name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  # Read: Trusted Publisher on GitHub & npm
  # https://docs.npmjs.com/trusted-publishers#supported-cicd-providers
  id-token: write  # Required for OIDC

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Install and cache nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      # We need npm@v~11 beacuse we use Trusted Publisher.
      - name: Install latest npm
        run: npm install -g npm@latest
      - name: Install packages
        run: pnpm i --ignore-scripts
      - name: Release check
        run: pnpm run ci-check
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
