name: "Snapshot Release@next"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Install and cache nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Install packages
        run: pnpm i --ignore-scripts
      - name: Release build
        run: pnpm build
      - name: Setup npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "Release @next"
        run: |
          pnpm changeset version --snapshot next
          pnpm changeset publish --no-git-tag --snapshot --tag next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
